### DISCUSSION TITLE
Enhance the support of shared configurations for nuget-package blueprint

### DISCUSSION THREAD

**Discussion by wpschaub** [WorkSafeBC-Common-Engineering/Common.Engineering.Discussion#9] [Updates - Templates]
@AndreasNVI has not only delivered a nuget-package blueprint, but has simplified the configuration and reduced the WASTE when supporting dozens to hundreds of NuGet packages. By default, every blueprint-based pipeline has a corresponding configuration file. When you have hundreds of NuGet packages in an Azure DevOps project this leads to duplication and therefore WASTE.

The nuget-package currently support two more configuration options:
- One configuration file shared across all pipelines
- One configuration file per portfolio shared across all pipelines within the portfolio

The secret sauce is in the https://github.com/WorkSafeBC-Common-Engineering/AzureDevOps.Automation.Pipeline.Templates.v2/blob/master/blueprints/nuget-package/azure-pipeline-nuget-package-control.yml template:

```
# VARIABLES
variables:
- ${{ if and( eq(parameters.suppressCD, false), eq(parameters.useDefaultConfig, true) ) }}:
  - template: /deploy/default.config/nuget-package-config.yml@CeConfiguration

- ${{ if and( eq(parameters.suppressCD, false), eq(parameters.useDefaultConfig, false), eq(parameters.usePortfolioConfig, true) ) }}:
  - template: /deploy/${{ lower(parameters.portfolioName) }}/nuget-package-config.yml@CeConfiguration

- ${{ if and( eq(parameters.suppressCD, false), eq(parameters.useDefaultConfig, false), eq(parameters.usePortfolioConfig, false) ) }}:
  - template: /deploy/${{ lower(parameters.portfolioName) }}/${{ lower(parameters.productName) }}-config.yml@CeConfiguration
```
